version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      aws-sdk:
        patterns:
          - "@aws-sdk/*"
          - "@smithy/*"
      dev-dependencies:
        dependency-type: "development"
        patterns:
          - "*"
      puppeteer:
        patterns:
          - "puppeteer"
          - "puppeteer-core"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
