name: az2aws
version: git
title: az2aws
summary: Use Azure AD SSO to log into the AWS via CLI.
description: |
  To configure the az2aws client run:-
  $ az2aws --configure
  Once az2aws is configured, you can log in. For the default profile, just run:-
  $ az2aws
license: MIT
contact: https://github.com/kuma0128/az2aws
issues: https://github.com/kuma0128/az2aws/issues
source-code: https://github.com/kuma0128/az2aws
website: https://github.com/kuma0128/az2aws
base: core22
confinement: strict

parts:
  az2aws:
    plugin: npm
    npm-include-node: true
    npm-node-version: "24"
    source: .

apps:
  az2aws:
    command: bin/az2aws
