name: az2aws
version: git
summary: Use Azure AD SSO to log into the AWS via CLI.
description: |
  To configure the az2aws client run:-
  $ az2aws --configure
  Once az2aws is configured, you can log in. For the default profile, just run:-
  $ az2aws
base: core22
confinement: strict

parts:
  az2aws:
    plugin: nodejs
    nodejs-version: "22"
    nodejs-package-manager: yarn
    source: .

apps:
  az2aws:
    command: az2aws
