name: Main

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-slim
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v5
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm lint
      - if: matrix.os == 'ubuntu-slim'
        run: pnpm test:coverage
      - if: matrix.os == 'windows-latest'
        run: pnpm test
      - name: Upload coverage to Codecov
        if: matrix.os == 'ubuntu-slim'
        uses: codecov/codecov-action@v6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info
          fail_ci_if_error: false
          verbose: true
      - run: pnpm build
